/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  testcpp                                */
/*      FILE         :  testcpp.cpp                            */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - F14                             */
/*      CPU TYPE     :  R5F10PPJ                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   
                                                                                            
                                                                                            
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/
//#include "Arduino.h"

#include "Arduino.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

// Weak empty variant initialization function.
// May be redefined by variant files.
void initVariant() __attribute__((weak));
void initVariant() { }

void setupUSB() __attribute__((weak));
void setupUSB() { }

int main(void)
{
	init();

	initVariant();

	setup();

    // TODO: add application code here
    for(;;) {
    	loop();
    }
  return 0;
}
