/*
  wiring.c - Partial implementation of the Wiring API for the ATmega8.
  Part of Arduino - http://www.arduino.cc/

  Copyright (c) 2005-2006 David A. Mellis

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General
  Public License along with this library; if not, write to the
  Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA  02111-1307  USA
*/

#include "wiring_private.h"
#include "r_cg_timer.h"
#ifndef IODEFINE_EXT_H
#include "iodefine_ext.h"
#endif
#include "interrupt_handlers.h"

// the prescaler is set so that timer0 ticks every 1 clock cycles, and the
// the overflow handler is called every 32 * 256 * 4 ticks. FIXME: Hossam: there is no overflow for now :(
#define MICROSECONDS_PER_TIMER0_OVERFLOW (clockCyclesToMicroseconds((uint16_t)32 * 256 * 4)) // TODO: Any: check our prescaler and the ticks

// the whole number of milliseconds per timer0 overflow
#define MILLIS_INC (uint8_t)(MICROSECONDS_PER_TIMER0_OVERFLOW / 1000)

// the fractional number of milliseconds per timer0 overflow. we shift right
// by three to fit these numbers into a byte. (for the clock speeds we care
// about - 8 and 16 MHz - this doesn't lose precision.)
#define FRACT_INC (uint8_t)((MICROSECONDS_PER_TIMER0_OVERFLOW % 1000) >> 3)
#define FRACT_MAX (1000 >> 3)

volatile unsigned long long timer0_overflow_count = 0;
volatile unsigned long long timer0_millis = 0;
static unsigned char timer0_fract = 0;

/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Valduino                               */
/*      FILE         :  vector_table.c                         */
/*      DESCRIPTION  :  Vector Table                           */
/*      CPU SERIES   :  RL78 - F14                             */
/*      CPU TYPE     :  R5F10PPJ                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

/************************************************************************/
/* Header file generated from device file:                              */
/*    DR5F10PPJ.DVF                                                     */
/*    V1.10 (2014/08/05)                                                */
/*    Copyright(C) 2014 Renesas                                         */
/* Tool Version: 3.1.1                                                  */
/* Date Generated: 2015/02/20                                           */
/************************************************************************/

/*
 * INT_SRO/INT_WDTI (0x4)
 */
void INT_WDTI (void) { }
//void INT_SRO (void) { }

/*
 * INT_LVI (0x6)
 */
void INT_LVI (void) { }

/*
 * INT_P0 (0x8)
 */
void INT_P0 (void) { }

/*
 * INT_P1 (0xA)
 */
void INT_P1 (void) { }

/*
 * INT_P2 (0xC)
 */
void INT_P2 (void) { }

/*
 * INT_P3 (0xE)
 */
void INT_P3 (void) { }

/*
 * INT_P4/INT_SPM (0x10)
 */
void INT_SPM (void) { }
//void INT_P4 (void) { }

/*
 * INT_CMP0/INT_P5 (0x12)
 */
void INT_P5 (void) { }
//void INT_CMP0 (void) { }

/*
 * INT_CLM/INT_P13 (0x14)
 */
void INT_P13 (void) { }
//void INT_CLM (void) { }

/*
 * INT_CSI00/INT_IIC00/INT_ST0 (0x16)
 */
void INT_ST0 (void) { }
//void INT_CSI00 (void) { }
//void INT_IIC00 (void) { }

/*
 * INT_CSI01/INT_IIC01/INT_SR0 (0x18)
 */
void INT_SR0 (void) { }
//void INT_CSI01 (void) { }
//void INT_IIC01 (void) { }

/*
 * INT_TRD0 (0x1A)
 */
void INT_TRD0 (void) {

	// copy these to local variables so they can be stored in registers
	// (volatile variables must be read from memory on every access)
	unsigned long m = timer0_millis;
	unsigned char f = timer0_fract;

	m += MILLIS_INC; // +1.024ms @16MHz prescaler 64
	f += FRACT_INC; // +3 @16MHz
	if (f >= FRACT_MAX) { // FACT_MAX = (1000>>3) = 125 it means it takes 42 overflow interrupt to make the condition true (3*42 = 126)
		f -= FRACT_MAX;
		m += 1;
	}

	timer0_fract = f;
	timer0_millis = m;
	timer0_overflow_count++;

	volatile uint8_t dummy; // Must read the status before clear it
	dummy = TRDSR0;
	TRDSR0 = 0;
}

/*
 * INT_TRD1 (0x1C)
 */
void INT_TRD1 (void) { }

/*
 * INT_TRJ0 (0x1E)
 */
void INT_TRJ0 (void) { }

/*
 * INT_RAM (0x20)
 */
void INT_RAM (void) { }

/*
 * INT_LIN0TRM (0x22)
 */
void INT_LIN0TRM (void) { }

/*
 * INT_LIN0RVC (0x24)
 */
void INT_LIN0RVC (void) { }

/*
 * INT_LIN0/INT_LIN0STA (0x26)
 */
void INT_LIN0STA (void) { }
//void INT_LIN0 (void) { }

/*
 * INT_IICA0 (0x28)
 */
void INT_IICA0 (void) { }

/*
 * INT_P8/INT_RTC (0x2A)
 */
void INT_RTC (void) { }
//void INT_P8 (void) { }

/*
 * INT_TM00 (0x2C)
 */
void INT_TM00 (void) { }

/*
 * INT_TM01 (0x2E)
 */
void INT_TM01 (void) { }

/*
 * INT_TM02 (0x30)
 */
void INT_TM02 (void) { }

/*
 * INT_TM03 (0x32)
 */
void INT_TM03 (void) { }

/*
 * INT_AD (0x34)
 */
void INT_AD (void) { }

/*
 * INT_P6/INT_TM11H (0x36)
 */
void INT_TM11H (void) { }
//void INT_P6 (void) { }

/*
 * INT_P7/INT_TM13H (0x38)
 */
void INT_TM13H (void) { }
//void INT_P7 (void) { }

/*
 * INT_P9/INT_TM01H (0x3A)
 */
void INT_TM01H (void) { }
//void INT_P9 (void) { }

/*
 * INT_P10/INT_TM03H (0x3C)
 */
void INT_TM03H (void) { }
//void INT_P10 (void) { }

/*
 * INT_CSI10/INT_IIC10/INT_ST1 (0x3E)
 */
void INT_ST1 (void) { }
//void INT_CSI10 (void) { }
//void INT_IIC10 (void) { }

/*
 * INT_CSI11/INT_IIC11/INT_SR1 (0x40)
 */
void INT_SR1 (void) { }
//void INT_CSI11 (void) { }
//void INT_IIC11 (void) { }

/*
 * INT_TM04 (0x42)
 */
void INT_TM04 (void) { }

/*
 * INT_TM05 (0x44)
 */
void INT_TM05 (void) { }

/*
 * INT_TM06 (0x46)
 */
void INT_TM06 (void) { }

/*
 * INT_TM07 (0x48)
 */
void INT_TM07 (void) { }

/*
 * INT_LIN0WUP/INT_P11 (0x4A)
 */
void INT_P11 (void) { }
//void INT_LIN0WUP (void) { }

/*
 * INT_KR (0x4C)
 */
void INT_KR (void) { }

/*
 * INT_CAN0ERR (0x4E)
 */
void INT_CAN0ERR (void) { }

/*
 * INT_CAN0WUP (0x50)
 */
void INT_CAN0WUP (void) { }

/*
 * INT_CAN0CFR (0x52)
 */
void INT_CAN0CFR (void) { }

/*
 * INT_CAN0TRM (0x54)
 */
void INT_CAN0TRM (void) { }

/*
 * INT_CANGRFR (0x56)
 */
void INT_CANGRFR (void) { }

/*
 * INT_CANGERR (0x58)
 */
void INT_CANGERR (void) { }

/*
 * INT_TM10 (0x5A)
 */
void INT_TM10 (void) { }

/*
 * INT_TM11 (0x5C)
 */
void INT_TM11 (void) { }

/*
 * INT_TM12 (0x5E)
 */
void INT_TM12 (void) { }

/*
 * INT_TM13 (0x60)
 */
void INT_TM13 (void) { }

/*
 * INT_FL (0x62)
 */
void INT_FL (void) { }

/*
 * INT_LIN1WUP/INT_P12 (0x64)
 */
void INT_P12 (void) { }
//void INT_LIN1WUP (void) { }

/*
 * INT_LIN1TRM (0x66)
 */
void INT_LIN1TRM (void) { }

/*
 * INT_LIN1RVC (0x68)
 */
void INT_LIN1RVC (void) { }

/*
 * INT_LIN1/INT_LIN1STA (0x6A)
 */
void INT_LIN1STA (void) { }
//void INT_LIN1 (void) { }

/*
 * INT_TM14 (0x6C)
 */
void INT_TM14 (void) { }

/*
 * INT_TM15 (0x6E)
 */
void INT_TM15 (void) { }

/*
 * INT_TM16 (0x70)
 */
void INT_TM16 (void) { }

/*
 * INT_TM17 (0x72)
 */
void INT_TM17 (void) { }

/*
 * INT_BRK_I (0x7E)
 */
void INT_BRK_I (void) { }


extern void PowerON_Reset (void);

const unsigned char Option_Bytes[]  __attribute__ ((section (".option_bytes"))) = {
	0xef, 0xff, 0xe8, 0x85
};

const unsigned char Security_Id[]  __attribute__ ((section (".security_id"))) = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

#define VEC          __attribute__ ((section (".vec")))
const void *HardwareVectors[] VEC = {
	// Address 0x0
	PowerON_Reset,
	// Secure for Debugging
	(void*)0xFFFF
};

#define VECT_SECT          __attribute__ ((section (".vects")))
const void *Vectors[] VECT_SECT = {
	//INT_SRO/INT_WDTI (0x4)
	INT_WDTI,
	//INT_LVI (0x6)
	INT_LVI,
	//INT_P0 (0x8)
	INT_P0,
	//INT_P1 (0xA)
	INT_P1,
	//INT_P2 (0xC)
	INT_P2,
	//INT_P3 (0xE)
	INT_P3,
	//INT_P4/INT_SPM (0x10)
	INT_SPM,
	//INT_CMP0/INT_P5 (0x12)
	INT_P5,
	//INT_CLM/INT_P13 (0x14)
	INT_P13,
	//INT_CSI00/INT_IIC00/INT_ST0 (0x16)
	INT_ST0,
	//INT_CSI01/INT_IIC01/INT_SR0 (0x18)
	INT_SR0,
	//INT_TRD0 (0x1A)
	INT_TRD0,
	//INT_TRD1 (0x1C)
	INT_TRD1,
	//INT_TRJ0 (0x1E)
	INT_TRJ0,
	//INT_RAM (0x20)
	INT_RAM,
	//INT_LIN0TRM (0x22)
	INT_LIN0TRM,
	//INT_LIN0RVC (0x24)
	INT_LIN0RVC,
	//INT_LIN0/INT_LIN0STA (0x26)
	INT_LIN0STA,
	//INT_IICA0 (0x28)
	INT_IICA0,
	//INT_P8/INT_RTC (0x2A)
	INT_RTC,
	//INT_TM00 (0x2C)
	INT_TM00,
	//INT_TM01 (0x2E)
	INT_TM01,
	//INT_TM02 (0x30)
	INT_TM02,
	//INT_TM03 (0x32)
	INT_TM03,
	//INT_AD (0x34)
	INT_AD,
	//INT_P6/INT_TM11H (0x36)
	INT_TM11H,
	//INT_P7/INT_TM13H (0x38)
	INT_TM13H,
	//INT_P9/INT_TM01H (0x3A)
	INT_TM01H,
	//INT_P10/INT_TM03H (0x3C)
	INT_TM03H,
	//INT_CSI10/INT_IIC10/INT_ST1 (0x3E)
	INT_ST1,
	//INT_CSI11/INT_IIC11/INT_SR1 (0x40)
	INT_SR1,
	//INT_TM04 (0x42)
	INT_TM04,
	//INT_TM05 (0x44)
	INT_TM05,
	//INT_TM06 (0x46)
	INT_TM06,
	//INT_TM07 (0x48)
	INT_TM07,
	//INT_LIN0WUP/INT_P11 (0x4A)
	INT_P11,
	//INT_KR (0x4C)
	INT_KR,
	//INT_CAN0ERR (0x4E)
	INT_CAN0ERR,
	//INT_CAN0WUP (0x50)
	INT_CAN0WUP,
	//INT_CAN0CFR (0x52)
	INT_CAN0CFR,
	//INT_CAN0TRM (0x54)
	INT_CAN0TRM,
	//INT_CANGRFR (0x56)
	INT_CANGRFR,
	//INT_CANGERR (0x58)
	INT_CANGERR,
	//INT_TM10 (0x5A)
	INT_TM10,
	//INT_TM11 (0x5C)
	INT_TM11,
	//INT_TM12 (0x5E)
	INT_TM12,
	//INT_TM13 (0x60)
	INT_TM13,
	//INT_FL (0x62)
	INT_FL,
	//INT_LIN1WUP/INT_P12 (0x64)
	INT_P12,
	//INT_LIN1TRM (0x66)
	INT_LIN1TRM,
	//INT_LIN1RVC (0x68)
	INT_LIN1RVC,
	//INT_LIN1/INT_LIN1STA (0x6A)
	INT_LIN1STA,
	//INT_TM14 (0x6C)
	INT_TM14,
	//INT_TM15 (0x6E)
	INT_TM15,
	//INT_TM16 (0x70)
	INT_TM16,
	//INT_TM17 (0x72)
	INT_TM17,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	//INT_BRK_I (0x7E)
	INT_BRK_I,
};

unsigned long millis()
{
	unsigned long m;
	//uint8_t oldSREG = SREG;

	// disable interrupts while we read timer0_millis or we might get an
	// inconsistent value (e.g. in the middle of a write to timer0_millis)
	cli();
	m = timer0_millis;
	sei();
	//SREG = oldSREG;

	return m;
}

// http://garretlab.web.fc2.com/arduino/inside/arduino/wiring.c/micros.html
unsigned long micros() {
	unsigned long long m;
	uint8_t /*oldSREG = SREG,*/ t;

	cli();
	m = timer0_overflow_count;
	t = TRD0; // TRD0 is the Timer 0 counter
	if ((TRDSR0_bit.no0) && (t < (1023))) //TRDSR0_bit.no4 OVF , TRDSR0_bit.no0 IMFA Compare match flag A
	{
		//m++;
		//TRDSR0 = 0;
	}

	//SREG = oldSREG;
	sei();
	//unsigned long reto = ((m << 15)/clockCyclesPerMicrosecond()) + (t/clockCyclesPerMicrosecond()) ;
	return ( (m << 10) + t) * (32/clockCyclesPerMicrosecond()); // (m*256 + t) * (prescaler / (F_CPU / 1000000) ) where t is the counter counts and m the number of overflow and 256 because 256 count per overflow
}

void delay(unsigned long ms)
{
	uint32_t start = (uint32_t)millis();

	while (ms > 0) {
		//yield();	//FIXME: add support for this function
		if (((uint32_t)millis() - start) >= 1) {
			ms--;
			start += 1;
		}
	}
}

///* Delay for the given number of microseconds.  Assumes a 1, 8, 12, 16, 20 or 24 MHz clock. */
//void delayMicroseconds(unsigned int us)
//{
//	// call = 4 cycles + 2 to 4 cycles to init us(2 for constant delay, 4 for variable)
//
//	// calling avrlib's delay_us() function with low values (e.g. 1 or
//	// 2 microseconds) gives delays longer than desired.
//	//delay_us(us);
//#if F_CPU >= 24000000L
//	// for the 24 MHz clock for the aventurous ones, trying to overclock
//
//	// zero delay fix
//	if (!us) return; //  = 3 cycles, (4 when true)
//
//	// the following loop takes a 1/6 of a microsecond (4 cycles)
//	// per iteration, so execute it six times for each microsecond of
//	// delay requested.
//	us *= 6; // x6 us, = 7 cycles
//
//	// account for the time taken in the preceeding commands.
//	// we just burned 22 (24) cycles above, remove 5, (5*4=20)
//	// us is at least 6 so we can substract 5
//	us -= 5; //=2 cycles
//
//#elif F_CPU >= 20000000L
//	// for the 20 MHz clock on rare Arduino boards
//
//	// for a one-microsecond delay, simply return.  the overhead
//	// of the function call takes 18 (20) cycles, which is 1us
//	__asm__ __volatile__ (
//		"nop" "\n\t"
//		"nop" "\n\t"
//		"nop" "\n\t"
//		"nop"); //just waiting 4 cycles
//	if (us <= 1) return; //  = 3 cycles, (4 when true)
//
//	// the following loop takes a 1/5 of a microsecond (4 cycles)
//	// per iteration, so execute it five times for each microsecond of
//	// delay requested.
//	us = (us << 2) + us; // x5 us, = 7 cycles
//
//	// account for the time taken in the preceeding commands.
//	// we just burned 26 (28) cycles above, remove 7, (7*4=28)
//	// us is at least 10 so we can substract 7
//	us -= 7; // 2 cycles
//
//#elif F_CPU >= 16000000L
//	// for the 16 MHz clock on most Arduino boards
//
//	// for a one-microsecond delay, simply return.  the overhead
//	// of the function call takes 14 (16) cycles, which is 1us
//	if (us <= 1) return; //  = 3 cycles, (4 when true)
//
//	// the following loop takes 1/4 of a microsecond (4 cycles)
//	// per iteration, so execute it four times for each microsecond of
//	// delay requested.
//	us <<= 2; // x4 us, = 4 cycles
//
//	// account for the time taken in the preceeding commands.
//	// we just burned 19 (21) cycles above, remove 5, (5*4=20)
//	// us is at least 8 so we can substract 5
//	us -= 5; // = 2 cycles,
//
//#elif F_CPU >= 12000000L
//	// for the 12 MHz clock if somebody is working with USB
//
//	// for a 1 microsecond delay, simply return.  the overhead
//	// of the function call takes 14 (16) cycles, which is 1.5us
//	if (us <= 1) return; //  = 3 cycles, (4 when true)
//
//	// the following loop takes 1/3 of a microsecond (4 cycles)
//	// per iteration, so execute it three times for each microsecond of
//	// delay requested.
//	us = (us << 1) + us; // x3 us, = 5 cycles
//
//	// account for the time taken in the preceeding commands.
//	// we just burned 20 (22) cycles above, remove 5, (5*4=20)
//	// us is at least 6 so we can substract 5
//	us -= 5; //2 cycles
//
//#elif F_CPU >= 8000000L
//	// for the 8 MHz internal clock
//
//	// for a 1 and 2 microsecond delay, simply return.  the overhead
//	// of the function call takes 14 (16) cycles, which is 2us
//	if (us <= 2) return; //  = 3 cycles, (4 when true)
//
//	// the following loop takes 1/2 of a microsecond (4 cycles)
//	// per iteration, so execute it twice for each microsecond of
//	// delay requested.
//	us <<= 1; //x2 us, = 2 cycles
//
//	// account for the time taken in the preceeding commands.
//	// we just burned 17 (19) cycles above, remove 4, (4*4=16)
//	// us is at least 6 so we can substract 4
//	us -= 4; // = 2 cycles
//
//#else
//	// for the 1 MHz internal clock (default settings for common Atmega microcontrollers)
//
//	// the overhead of the function calls is 14 (16) cycles
//	if (us <= 16) return; //= 3 cycles, (4 when true)
//	if (us <= 25) return; //= 3 cycles, (4 when true), (must be at least 25 if we want to substract 22)
//
//	// compensate for the time taken by the preceeding and next commands (about 22 cycles)
//	us -= 22; // = 2 cycles
//	// the following loop takes 4 microseconds (4 cycles)
//	// per iteration, so execute it us/4 times
//	// us is at least 4, divided by 4 gives us 1 (no zero delay bug)
//	us >>= 2; // us div 4, = 4 cycles
//
//
//#endif
//
//	// busy wait
//	__asm__ __volatile__ (
//		"1: sbiw %0,1" "\n\t" // 2 cycles
//		"brne 1b" : "=w" (us) : "0" (us) // 2 cycles
//	);
//	// return = 4 cycles
//}

void init()
{
	// this needs to be called before setup() or some functions won't
	// work there
	sei();
	//EI();
	/*Timers init*/

	/*TAU0 Create*/

    TAU0EN = 1U;    /* supplies input clock */
    TPS0 = _0000_TAU_CKM0_FCLK_0 | _0000_TAU_CKM1_FCLK_0 | _0000_TAU_CKM2_FCLK_1 | _0000_TAU_CKM3_FCLK_8;
    /* Stop all channels */
    TT0 = _0001_TAU_CH0_STOP_TRG_ON | _0002_TAU_CH1_STOP_TRG_ON | _0004_TAU_CH2_STOP_TRG_ON |
          _0008_TAU_CH3_STOP_TRG_ON | _0010_TAU_CH4_STOP_TRG_ON | _0020_TAU_CH5_STOP_TRG_ON |
          _0040_TAU_CH6_STOP_TRG_ON | _0080_TAU_CH7_STOP_TRG_ON | _0200_TAU_CH1_H8_STOP_TRG_ON |
          _0800_TAU_CH3_H8_STOP_TRG_ON;
    PWMDLY1 = _0000_TAU_PWM_DELAY_CLEAR;    /* clear PWM output delay */
    /* Mask channel 0 interrupt */
    TMMK00 = 1U;    /* disable INTTM00 interrupt */
    TMIF00 = 0U;    /* clear INTTM00 interrupt flag */
    /* Mask channel 1 interrupt */
    TMMK01 = 1U;    /* disable INTTM01 interrupt */
    TMIF01 = 0U;    /* clear INTTM01 interrupt flag */
    /* Mask channel 1 higher 8 bits interrupt */
    TMMK01H = 1U;    /* disable INTTM01H interrupt */
    TMIF01H = 0U;    /* clear INTTM01H interrupt flag */
    /* Mask channel 2 interrupt */
    TMMK02 = 1U;    /* disable INTTM02 interrupt */
    TMIF02 = 0U;    /* clear INTTM02 interrupt flag */
    /* Mask channel 3 interrupt */
    TMMK03 = 1U;    /* disable INTTM03 interrupt */
    TMIF03 = 0U;    /* clear INTTM03 interrupt flag */
    /* Mask channel 3 higher 8 bits interrupt */
    TMMK03H = 1U;    /* disable INTTM03H interrupt */
    TMIF03H = 0U;    /* clear INTTM03H interrupt flag */
    /* Mask channel 4 interrupt */
    TMMK04 = 1U;    /* disable INTTM04 interrupt */
    TMIF04 = 0U;    /* clear INTTM04 interrupt flag */
    /* Mask channel 5 interrupt */
    TMMK05 = 1U;    /* disable INTTM05 interrupt */
    TMIF05 = 0U;    /* clear INTTM05 interrupt flag */
    /* Mask channel 6 interrupt */
    TMMK06 = 1U;    /* disable INTTM06 interrupt */
    TMIF06 = 0U;    /* clear INTTM06 interrupt flag */
    /* Mask channel 7 interrupt */
    TMMK07 = 1U;    /* disable INTTM07 interrupt */
    TMIF07 = 0U;    /* clear INTTM07 interrupt flag */
    /* Set INTTM02 low priority */
    TMPR102 = 1U;
    TMPR002 = 1U;
    /* Set INTTM03 low priority */
    TMPR103 = 1U;
    TMPR003 = 1U;
    /* Set INTTM04 low priority */
    TMPR104 = 1U;
    TMPR004 = 1U;
    /* Set INTTM06 low priority */
    TMPR106 = 1U;
    TMPR006 = 1U;
    /* Set INTTM07 low priority */
    TMPR107 = 1U;
    TMPR007 = 1U;
    /* Channel 2 is used as master channel for PWM output function */
    TMR02 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0800_TAU_COMBINATION_MASTER |
            _0000_TAU_TRIGGER_SOFTWARE | _0001_TAU_MODE_PWM_MASTER;
    TDR02 = _FEFF_TAU_TDR02_VALUE;
    TOM0 &= ~_0004_TAU_CH2_OUTPUT_COMBIN;
    TOL0 &= ~_0004_TAU_CH2_OUTPUT_LEVEL_L;
    TO0 &= ~_0004_TAU_CH2_OUTPUT_VALUE_1;
    TOE0 &= ~_0004_TAU_CH2_OUTPUT_ENABLE;
    /* Channel 3 is used as slave channel for PWM output function */
    TMR03 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR03 = _7F80_TAU_TDR03_VALUE;
    TOM0 |= _0008_TAU_CH3_OUTPUT_COMBIN;
    TOL0 &= ~_0008_TAU_CH3_OUTPUT_LEVEL_L;
    TO0 &= ~_0008_TAU_CH3_OUTPUT_VALUE_1;
    PWMDLY1 |= _0000_TO03_OUTPUT_DELAY_0;
    TOE0 |= _0008_TAU_CH3_OUTPUT_ENABLE;
    /* Channel 4 is used as slave channel for PWM output function */
    TMR04 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR04 = _7F80_TAU_TDR04_VALUE;
    TOM0 |= _0010_TAU_CH4_OUTPUT_COMBIN;
    TOL0 &= ~_0010_TAU_CH4_OUTPUT_LEVEL_L;
    TO0 &= ~_0010_TAU_CH4_OUTPUT_VALUE_1;
    PWMDLY1 |= _0000_TO04_OUTPUT_DELAY_0;
    TOE0 |= _0010_TAU_CH4_OUTPUT_ENABLE;
    /* Channel 6 is used as slave channel for PWM output function */
    TMR06 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR06 = _7F80_TAU_TDR06_VALUE;
    TOM0 |= _0040_TAU_CH6_OUTPUT_COMBIN;
    TOL0 &= ~_0040_TAU_CH6_OUTPUT_LEVEL_L;
    TO0 &= ~_0040_TAU_CH6_OUTPUT_VALUE_1;
    PWMDLY1 |= _0000_TO06_OUTPUT_DELAY_0;
    TOE0 |= _0040_TAU_CH6_OUTPUT_ENABLE;
    /* Channel 7 is used as slave channel for PWM output function */
    TMR07 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR07 = _7F80_TAU_TDR07_VALUE;
    TOM0 |= _0080_TAU_CH7_OUTPUT_COMBIN;
    TOL0 &= ~_0080_TAU_CH7_OUTPUT_LEVEL_L;
    TO0 &= ~_0080_TAU_CH7_OUTPUT_VALUE_1;
    PWMDLY1 |= _0000_TO07_OUTPUT_DELAY_0;
    TOE0 |= _0080_TAU_CH7_OUTPUT_ENABLE;
    /* Set TO03 pin */
    PMC12 &= 0xDFU;
    P12 &= 0xDFU;
    PM12 &= 0xDFU;
    /* Set TO04 pin */
    POM1 &= 0xF7U;
    P1 &= 0xF7U;
    PM1 &= 0xF7U;
    /* Set TO06 pin */
    POM1 &= 0xEFU;
    P1 &= 0xEFU;
    PM1 &= 0xEFU;
    /* Set TO07 pin */
    POM12 &= 0xFEU;
    PMC12 &= 0xFEU;
    P12 &= 0xFEU;
    PM12 &= 0xFEU;


	/*TAU1 Create*/

    TAU1EN = 1U;    /* supplies input clock */
    TPS1 = _0000_TAU_CKM0_FCLK_0 | _0000_TAU_CKM1_FCLK_0 | _0000_TAU_CKM2_FCLK_1 | _0000_TAU_CKM3_FCLK_8;
    /* Stop all channels */
    TT1 = _0001_TAU_CH0_STOP_TRG_ON | _0002_TAU_CH1_STOP_TRG_ON | _0004_TAU_CH2_STOP_TRG_ON |
          _0008_TAU_CH3_STOP_TRG_ON | _0010_TAU_CH4_STOP_TRG_ON | _0020_TAU_CH5_STOP_TRG_ON |
          _0040_TAU_CH6_STOP_TRG_ON | _0080_TAU_CH7_STOP_TRG_ON | _0200_TAU_CH1_H8_STOP_TRG_ON |
          _0800_TAU_CH3_H8_STOP_TRG_ON;
    PWMDLY2 = _0000_TAU_PWM_DELAY_CLEAR;    /* clear PWM output delay */
    /* Mask channel 0 interrupt */
    TMMK10 = 1U;    /* disable INTTM10 interrupt */
    TMIF10 = 0U;    /* clear INTTM10 interrupt flag */
    /* Mask channel 1 interrupt */
    TMMK11 = 1U;    /* disable INTTM11 interrupt */
    TMIF11 = 0U;    /* clear INTTM11 interrupt flag */
    /* Mask channel 1 higher 8 bits interrupt */
    TMMK11H = 1U;    /* disable INTTM11H interrupt */
    TMIF11H = 0U;    /* clear INTTM11H interrupt flag */
    /* Mask channel 2 interrupt */
    TMMK12 = 1U;    /* disable INTTM12 interrupt */
    TMIF12 = 0U;    /* clear INTTM12 interrupt flag */
    /* Mask channel 3 interrupt */
    TMMK13 = 1U;    /* disable INTTM13 interrupt */
    TMIF13 = 0U;    /* clear INTTM13 interrupt flag */
    /* Mask channel 3 higher 8 bits interrupt */
    TMMK13H = 1U;    /* disable INTTM13H interrupt */
    TMIF13H = 0U;    /* clear INTTM13H interrupt flag */
    /* Mask channel 4 interrupt */
    TMMK14 = 1U;    /* disable INTTM14 interrupt */
    TMIF14 = 0U;    /* clear INTTM14 interrupt flag */
    /* Mask channel 5 interrupt */
    TMMK15 = 1U;    /* disable INTTM15 interrupt */
    TMIF15 = 0U;    /* clear INTTM15 interrupt flag */
    /* Mask channel 6 interrupt */
    TMMK16 = 1U;    /* disable INTTM16 interrupt */
    TMIF16 = 0U;    /* clear INTTM16 interrupt flag */
    /* Mask channel 7 interrupt */
    TMMK17 = 1U;    /* disable INTTM17 interrupt */
    TMIF17 = 0U;    /* clear INTTM17 interrupt flag */
    /* Set INTTM10 low priority */
    TMPR110 = 1U;
    TMPR010 = 1U;
    /* Set INTTM11 low priority */
    TMPR111 = 1U;
    TMPR011 = 1U;
    /* Set INTTM12 low priority */
    TMPR112 = 1U;
    TMPR012 = 1U;
    /* Set INTTM13 low priority */
    TMPR113 = 1U;
    TMPR013 = 1U;
    /* Set INTTM14 low priority */
    TMPR114 = 1U;
    TMPR014 = 1U;
    /* Set INTTM15 low priority */
    TMPR115 = 1U;
    TMPR015 = 1U;
    /* Set INTTM16 low priority */
    TMPR116 = 1U;
    TMPR016 = 1U;
    /* Set INTTM17 low priority */
    TMPR117 = 1U;
    TMPR017 = 1U;
    /* Channel 0 is used as master channel for PWM output function */
    TMR10 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_TRIGGER_SOFTWARE |
            _0001_TAU_MODE_PWM_MASTER;
    TDR10 = _FEFF_TAU_TDR10_VALUE;
    TO1 &= ~_0001_TAU_CH0_OUTPUT_VALUE_1;
    TOE1 &= ~_0001_TAU_CH0_OUTPUT_ENABLE;
    /* Channel 1 is used as slave channel for PWM output function */
    TMR11 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR11 = _7F80_TAU_TDR11_VALUE;
    TOM1 |= _0002_TAU_CH1_OUTPUT_COMBIN;
    TOL1 &= ~_0002_TAU_CH1_OUTPUT_LEVEL_L;
    TO1 &= ~_0002_TAU_CH1_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO11_OUTPUT_DELAY_0;
    TOE1 |= _0002_TAU_CH1_OUTPUT_ENABLE;
    /* Channel 2 is used as slave channel for PWM output function */
    TMR12 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR12 = _7F80_TAU_TDR12_VALUE;
    TOM1 |= _0004_TAU_CH2_OUTPUT_COMBIN;
    TOL1 &= ~_0004_TAU_CH2_OUTPUT_LEVEL_L;
    TO1 &= ~_0004_TAU_CH2_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO12_OUTPUT_DELAY_0;
    TOE1 |= _0004_TAU_CH2_OUTPUT_ENABLE;
    /* Channel 3 is used as slave channel for PWM output function */
    TMR13 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR13 = _7F80_TAU_TDR13_VALUE;
    TOM1 |= _0008_TAU_CH3_OUTPUT_COMBIN;
    TOL1 &= ~_0008_TAU_CH3_OUTPUT_LEVEL_L;
    TO1 &= ~_0008_TAU_CH3_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO13_OUTPUT_DELAY_0;
    TOE1 |= _0008_TAU_CH3_OUTPUT_ENABLE;
    /* Channel 4 is used as slave channel for PWM output function */
    TMR14 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR14 = _7F80_TAU_TDR14_VALUE;
    TOM1 |= _0010_TAU_CH4_OUTPUT_COMBIN;
    TOL1 &= ~_0010_TAU_CH4_OUTPUT_LEVEL_L;
    TO1 &= ~_0010_TAU_CH4_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO14_OUTPUT_DELAY_0;
    TOE1 |= _0010_TAU_CH4_OUTPUT_ENABLE;
    /* Channel 5 is used as slave channel for PWM output function */
    TMR15 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR15 = _7F80_TAU_TDR15_VALUE;
    TOM1 |= _0020_TAU_CH5_OUTPUT_COMBIN;
    TOL1 &= ~_0020_TAU_CH5_OUTPUT_LEVEL_L;
    TO1 &= ~_0020_TAU_CH5_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO15_OUTPUT_DELAY_0;
    TOE1 |= _0020_TAU_CH5_OUTPUT_ENABLE;
    /* Channel 6 is used as slave channel for PWM output function */
    TMR16 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR16 = _7F80_TAU_TDR16_VALUE;
    TOM1 |= _0040_TAU_CH6_OUTPUT_COMBIN;
    TOL1 &= ~_0040_TAU_CH6_OUTPUT_LEVEL_L;
    TO1 &= ~_0040_TAU_CH6_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO16_OUTPUT_DELAY_0;
    TOE1 |= _0040_TAU_CH6_OUTPUT_ENABLE;
    /* Channel 7 is used as slave channel for PWM output function */
    TMR17 = _0000_TAU_CLOCK_SELECT_CKM0 | _0000_TAU_CLOCK_MODE_CKS | _0000_TAU_COMBINATION_SLAVE |
            _0400_TAU_TRIGGER_MASTER_INT | _0009_TAU_MODE_PWM_SLAVE;
    TDR17 = _7F80_TAU_TDR17_VALUE;
    TOM1 |= _0080_TAU_CH7_OUTPUT_COMBIN;
    TOL1 &= ~_0080_TAU_CH7_OUTPUT_LEVEL_L;
    TO1 &= ~_0080_TAU_CH7_OUTPUT_VALUE_1;
    PWMDLY2 |= _0000_TO17_OUTPUT_DELAY_0;
    TOE1 |= _0080_TAU_CH7_OUTPUT_ENABLE;
    /* Set TO11 pin */
    POM1 &= 0xFBU;
    P1 &= 0xFBU;
    PM1 &= 0xFBU;
    /* Set TO12 pin */
    POM1 &= 0xFDU;
    P1 &= 0xFDU;
    PM1 &= 0xFDU;
    /* Set TO13 pin */
    POM1 &= 0xFEU;
    P1 &= 0xFEU;
    PM1 &= 0xFEU;
    /* Set TO14 pin */
    P3 &= 0xFDU;
    PM3 &= 0xFDU;
    /* Set TO15 pin */
    POM7 &= 0xFEU;
    PMC7 &= 0xFEU;
    P7 &= 0xFEU;
    PM7 &= 0xFEU;
    /* Set TO16 pin */
    P3 &= 0xFBU;
    PM3 &= 0xFBU;
    /* Set TO17 pin */
    POM7 &= 0xFDU;
    PMC7 &= 0xFDU;
    P7 &= 0xFDU;
    PM7 &= 0xFDU;

    /* RD0 Create */
    TRD0EN = 1U;    /* enable input clock supply */
    TRDSTR |= _04_TMRD_TRD0_COUNT_CONTINUES | _08_TMRD_TRD1_COUNT_CONTINUES;
    TRDSTR &= (uint8_t)~_03_TRD_COUNT_STATR_INITIAL_VALUE;  /* disable TMRD operation */
    PWMDLY0 = _0000_TMRD_PWM_DELAY_CLEAR;    /* clear PWM output delay */
    TRDMK0 = 1U;    /* disable TMRD0 interrupt */
    TRDIF0 = 0U;    /* clear TMRD0 interrupt flag */
    TRDMK1 = 1U;    /* disable TMRD1 interrupt */
    TRDIF1 = 0U;    /* clear TMRD1 interrupt flag */
    /* Set INTTRD0 low priority */
    TRDPR10 = 1U;
    TRDPR00 = 1U;
    TRDMR = _00_TMRD_TRDGRC0_GENERAL | _00_TMRD_TRDGRD0_GENERAL | _00_TMRD_TRDGRC1_GENERAL | _00_TMRD_TRDGRD1_GENERAL;
    TRDPMR = _10_TMRD_TRDIOB1_PWM_MODE | _40_TMRD_TRDIOD1_PWM_MODE;
    TRDDF0 = _00_TMRD_TRDIOD_FORCEDCUTOFF_DISABLE | _00_TMRD_TRDIOC_FORCEDCUTOFF_DISABLE |
             _00_TMRD_TRDIOB_FORCEDCUTOFF_DISABLE;
    TRDDF1 = _00_TMRD_TRDIOD_FORCEDCUTOFF_DISABLE | _00_TMRD_TRDIOC_FORCEDCUTOFF_DISABLE |
             _00_TMRD_TRDIOB_FORCEDCUTOFF_DISABLE;
    PWMDLY0 = _0000_TMRD_TRDIOB1_OUTPUT_DELAY_0 | _0000_TMRD_TRDIOD1_OUTPUT_DELAY_0;
    TRDOER1 = _01_TMRD_TRDIOA0_OUTPUT_DISABLE | _02_TMRD_TRDIOB0_OUTPUT_DISABLE | _04_TMRD_TRDIOC0_OUTPUT_DISABLE |
              _08_TMRD_TRDIOD0_OUTPUT_DISABLE | _10_TMRD_TRDIOA1_OUTPUT_DISABLE | _20_TMRD_TRDIOB1_OUTPUT_DISABLE |
              _40_TMRD_TRDIOC1_OUTPUT_DISABLE | _80_TMRD_TRDIOD1_OUTPUT_DISABLE;

    TRDOCR = _00_TMRD_TRDIOB1_INITIAL_OUTPUT_L | _00_TMRD_TRDIOD1_INITIAL_OUTPUT_L;
    TRDCR0 = _04_TMRD_INTERNAL_CLOCK_F32 | _20_TMRD_COUNTER_CLEAR_TRDGRA;
    TRDCR1 = _04_TMRD_INTERNAL_CLOCK_F32 | _20_TMRD_COUNTER_CLEAR_TRDGRA;
    TRDIER0 = _01_TMRD_IMIA_ENABLE | _00_TMRD_IMIB_DISABLE | _00_TMRD_IMIC_DISABLE | _00_TMRD_IMID_DISABLE |
              _00_TMRD_OVIE_DISABLE;
    TRDIER1 = _00_TMRD_IMIA_DISABLE | _00_TMRD_IMIB_DISABLE | _00_TMRD_IMIC_DISABLE | _00_TMRD_IMID_DISABLE |
              _00_TMRD_OVIE_DISABLE;
    TRDPOCR1 = _00_TMRD_TRDIOB_OUTPUT_ACTIVE_L | _00_TMRD_TRDIOD_OUTPUT_ACTIVE_L;

    //TRDGRA0 = _7FFF_TMRD_TRDGRA0_VALUE;
	TRDGRA0 = 256*4;//256*64*2;//0xffff;//0x7FFF; //generate the 1024 tick with 32 prescaler
	//TRDGRA1 = _3FF_TMRD_TRDGRA1_VALUE;

	TRDGRA1 = 0x3ff;//0x3FF; // 0x3FF 1ms period for TRDGRB1 & TRDGRD1
	TRDGRB1 = 0x3FF/2-1; //MCU51
	TRDGRD1 = 0x3FF/2-1; // MCU50 //Maximum Value 0x3ff -1

	/* Set TRDIOB1 pin */
//    POM1 &= 0x7FU;
//    PM1 &= 0x7FU;
//    P1 &= 0x7FU;

    /* Set TRDIOD1 pin */
//    PM3 &= 0xFEU;
//    P3 &= 0xFEU;

    volatile uint8_t trdsr_dummy;

	TRDIF0 = 0U;    /* clear TMRD0 interrupt flag */
	trdsr_dummy = TRDSR0; /* read TRDSR0 before write 0 */
	TRDSR0 = 0x00U; /* clear TRD0 each interrupt request */
	TRDMK0 = 0U;    /* enable TMRD0 interrupt */
    // Start TRDGRA0 required for millis and micros functions
    TRDSTR |= _BV(2); // Enable CSEL0
    TRDSTR |= _BV(0); // Start TRD0 (TSTART0)






//    TMIF00 = 0U;    /* clear INTTM00 interrupt flag */
//	TMMK00 = 0U;    /* enable INTTM00 interrupt */
//	TS0 |= _BV(0);


//    TMIF00 = 0U;    /* clear INTTM00 interrupt flag */
//    TMMK00 = 0U;    /* enable INTTM00 interrupt */
//    TMIF01 = 0U;    /* clear INTTM01 interrupt flag */
//    TMMK01 = 0U;    /* enable INTTM01 interrupt */
//    TOE0 |= _0002_TAU_CH1_OUTPUT_ENABLE;
//    TS0 |= _0001_TAU_CH0_START_TRG_ON | _0002_TAU_CH1_START_TRG_ON;

}
